<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSvhiHQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSvhiHQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSvhiHQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSvhiHQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSvhiHQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PSvhiHQ',
    'container.build_id' => '6edb2579',
    'container.build_time' => 1617798951,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSvhiHQ');
