services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Command\:
        resource: '../../src/Command/*'
    
    App\Command\ImportArchiveCommand:
        arguments:
            $mapper: '@App\Import\Mapper\ChainMapper'
